### ISSUE TITLE
Atmosphere not getting reset.

### ISSUE THREAD

**Issue by shubhanshu786** [mracette/soundscape#11]
![Screenshot_20190906-202321](https://user-images.githubusercontent.com/26665687/64427659-51806280-d0e4-11e9-9cc6-25f9fd901e91.jpg)
Even after pressing reset button multiple times, atmosphere is showing 1/3, while none of them is select. 
I pressed number of different voices all together. Then such thing happened.

**Comment by mracette** [comment]
thanks for filing this! 
will take a look over the weekend and see what I can do.

**Comment by mracette** [comment]
This has been addressed in the 2.0.0 release.
