### ISSUE TITLE
Memory leaking issues

### ISSUE THREAD

**Issue by Deathray-II** [mracette/soundscape#12]
It seems that the program if left open long enough on random is starts to leak memory.

Tested in Chromium Version 80.0.3987.116 on Arch Linux on kernel version 5.5.4-arch1-1.
it seems that whenever the soundscape is left open long enough it slowly leaks memory:
Right before I turned on the background mode in the morning soundscape it was using 300MB of RAM.
After running  it for roughly half an hour it was using up 1GB of RAM.
It also seems that throughout all of this the CPU usage slowly increases going from 6% to 11% on the first test.
Repeating the same test in the moonrise soundscape started out with the same 300MB or RAM being used and after 25 minutes was using 1.2GB of RAM
Monitoring the memory of the Chromium tab it seems that the jumps in memory roughly coincide with when a new sound starts playing.

Tested in Firefox 74.0b4 on on Arch Linux on kernel version 5.5.4-arch1-1.
Right before I turn on background mode in Morning this Firefox tab is using roughly 330MB of RAM.
I had to stop it after 10 minutes already as it was using up 2.1GB of RAM and things were getting out of sync with each other.
It also seems that the CPU usage increased here as well, starting off at roughly 8% and ending at about 13%.
Repeating the same test in the moonrise soundscape started out with roughly 290MB of RAM being used and climbed up to about 2GB of RAM used after 10 minutes.
Also here the CPU usage went from about 8% to 13%.
In Firefox when large amounts of memory start to be leaked it seems that it also speeds up: at 1.8GB it took roughly 30 seconds to reach 2GB being used.

This issue may also be related to issue #7 because once the site starts using a lot of RAM and more CPU the visuals go from being smooth to being frozen or very choppy.

**Comment by mracette** [comment]
Thanks for running these tests, they're really specific and helpful. I'm going to prioritize this issue as I think it could be root cause for some others.

**Comment by mracette** [comment]
@Deathray-II I found and addressed a memory leak, and a few other minor performance issues that should lighten the load on the CPU (https://github.com/mracette/soundscape/pull/21/files)

If you have the time, I'd be curious to hear how this version compares to your earlier benchmarks. It's live now at dev.soundscape.world

I haven't done extensive testing but this does reduce memory usage significantly on my machine.
